sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - "node"
  - "6"
  - "6.1"
  - "6.0"
  - "5"
  - "5.1"
  - "4"
  - "4.2"
  - "4.1"
  - "4.0"
before_script:
  - make
script:
  - make test
